[package]
name = "wifirst-autologin"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
playwright = "0.0.20"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.40.0"

[profile.release]
opt-level = 3